### ISSUE TITLE
Restore classic event emitter interface

### ISSUE THREAD

**Issue by ghost** [plediii/HevEmitter#9]
The classic node event emitter accepts functions with multiple argument lengths.  This has been disabled for HevEmitter in order to allow callback functions.  The classic interface can be restored by requiring functions with callbacks to be hooked using a different function.  `emitter.on` would be used strictly for synchronous listeners, while `emitter.intercept` would be used for functions with callbacks.

**Comment by plediii** [comment]
Classic event emitter works in 1.x
